project:
  type: website

website:
  title: "**Alfred Appiah**"
  site-url: https://alfredappiah.com
  description: "Alfred Appiah's personal blog to talk about Ghanaian public policy issues purely from a data analytics perspectives"
  navbar:
    right:
      - text: About
        href: about.qmd
      - text: Blog
        href: blog.qmd
      - icon: github
        href: https://github.com/aappiah17
      - icon: twitter
        href: https://twitter.com/CallmeAlfredo
      - icon: rss
        href: blog.xml
  open-graph: true
  twitter-card: true
  cookie-consent: true
  google-analytics: "G-7371CL3CP9"
format:
  html:
    theme: theme.scss
    




